-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 09:22:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema harmony
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema harmony
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `harmony` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `harmony` ;

-- -----------------------------------------------------
-- Table `harmony`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`Organization` (
  `OrganizationId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `OrganizationName` VARCHAR(128) NOT NULL,
  `PublicKey` BLOB NULL,
  PRIMARY KEY (`OrganizationId`),
  UNIQUE INDEX `OrganizationName_UNIQUE` (`OrganizationName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`User` (
  `UserId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(128) NOT NULL,
  `Password` TINYBLOB NOT NULL,
  `OrganizationId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_User_Organization_idx` (`OrganizationId` ASC) VISIBLE,
  CONSTRAINT `fk_User_Organization`
    FOREIGN KEY (`OrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`UserSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`UserSession` (
  `UserId` BIGINT UNSIGNED NOT NULL,
  `Session` CHAR(36) NOT NULL,
  `LoginDate` DATETIME NOT NULL,
  PRIMARY KEY (`UserId`, `Session`),
  CONSTRAINT `fk_UserSession_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `harmony`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`OrganizationIdentifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`OrganizationIdentifier` (
  `OrganizationId` BIGINT UNSIGNED NOT NULL,
  `Code` VARCHAR(128) NOT NULL,
  `Type` ENUM('UUID', 'SGLN', 'LEI', 'SupplierSpecific', 'BuyerSpecific') NOT NULL,
  PRIMARY KEY (`OrganizationId`, `Code`),
  CONSTRAINT `fk_OrganizationIdentifier_Organization1`
    FOREIGN KEY (`OrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`Product` (
  `ProductId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(128) NOT NULL,
  `OrganizationId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ProductId`),
  INDEX `fk_Product_Organization1_idx` (`OrganizationId` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Organization1`
    FOREIGN KEY (`OrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`ProductIdentifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`ProductIdentifier` (
  `ProductId` BIGINT UNSIGNED NOT NULL,
  `Code` VARCHAR(128) NOT NULL,
  `Type` ENUM('UUID', 'SGTIN', 'SupplierSpecific', 'BuyerSpecific') NOT NULL,
  PRIMARY KEY (`ProductId`, `Code`),
  CONSTRAINT `fk_ProductIdentifier_Product1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `harmony`.`Product` (`ProductId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`ProductFootprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`ProductFootprint` (
  `ProductFootprintId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DataId` CHAR(36) NOT NULL,
  `ProductId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ProductFootprintId`),
  UNIQUE INDEX `DataId_UNIQUE` (`DataId` ASC) VISIBLE,
  INDEX `fk_ProductFootprint_Product1_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `fk_ProductFootprint_Product1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `harmony`.`Product` (`ProductId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`DataSource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`DataSource` (
  `DataSourceId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DataSourceType` ENUM('Pathfinder') NOT NULL DEFAULT 'Pathfinder',
  `UserName` VARCHAR(128) NOT NULL,
  `Password` TINYBLOB NOT NULL,
  `OrganizationId` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`DataSourceId`),
  INDEX `fk_DataSource_Organization1_idx` (`OrganizationId` ASC) VISIBLE,
  CONSTRAINT `fk_DataSource_Organization1`
    FOREIGN KEY (`OrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`Endpoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`Endpoint` (
  `DataSourceId` BIGINT UNSIGNED NOT NULL,
  `Type` ENUM('Authenticate', 'GetFootprints', 'UpdateEvent') NOT NULL,
  `Url` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`DataSourceId`, `Type`),
  CONSTRAINT `fk_Endpoint_DataSource1`
    FOREIGN KEY (`DataSourceId`)
    REFERENCES `harmony`.`DataSource` (`DataSourceId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `harmony`.`Request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harmony`.`Request` (
  `RequestId` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RequestType` ENUM('Contract') NOT NULL,
  `EventId` VARCHAR(128) NOT NULL,
  `Source` VARCHAR(256) NOT NULL,
  `RequestorOrganizationId` BIGINT UNSIGNED NOT NULL,
  `RequesteeOrganizationId` BIGINT UNSIGNED NOT NULL,
  `UpdatedTime` DATETIME NOT NULL,
  PRIMARY KEY (`RequestId`),
  INDEX `fk_Request_Organization1_idx` (`RequestorOrganizationId` ASC) VISIBLE,
  INDEX `fk_Request_Organization2_idx` (`RequesteeOrganizationId` ASC) VISIBLE,
  CONSTRAINT `fk_Request_Organization1`
    FOREIGN KEY (`RequestorOrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Organization2`
    FOREIGN KEY (`RequesteeOrganizationId`)
    REFERENCES `harmony`.`Organization` (`OrganizationId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
